### ISSUE TITLE
Cannot connect the test net rpc

### ISSUE THREAD

**Issue by madeshv5543** [ruimarinho/bitcoin-core#110]
err { Error: Parse Error
    at Socket.socketOnData (_http_client.js:442:20)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:94:17) bytesParsed: 0, code: 'HPE_INVALID_CONSTANT' }

**Comment by pedrobranco** [comment]
![confused](https://user-images.githubusercontent.com/4319748/68484540-59b86380-0235-11ea-8956-090424c4d0af.gif)

I think I will need more information to help you...:
- Maybe the `node --version`, setup of your client / node, other useful information?
- Have you tried to connect with your bitcoin-core node using `bitcoin-cli`?
