### ISSUE TITLE
(node:50292) UnhandledPromiseRejectionWarning: Error: socket hang up

### ISSUE THREAD

**Issue by Dkdaniz** [ruimarinho/bitcoin-core#121]
Hi, I have the following mistake:

`(node:51077) UnhandledPromiseRejectionWarning: Error: socket hang up
    at connResetException (internal/errors.js:613:14)
    at Socket.socketOnEnd (_http_client.js:493:23)
    at Socket.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1226:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(Use `node --trace-warnings ...` to show where the warning was created)`

Node: 12
OS: MacOs Catalina 10.15

### My bitcoin.config:

```logips=1

testnet=1

rpcauth=user:Hash

server=1

rest=1

[main]

[test]
deprecatedrpc=accounts
deprecatedrpc=addwitnessaddress
deprecatedrpc=signrawtransaction
deprecatedrpc=validateaddress

rpcallowip=45.255.237.23
rpcallowip=0.0.0.0/0
rpcbind=127.0.0.1

[regtest]```

Can someone help me?

**Comment by Dkdaniz** [comment]
The error occurs because the door is not open, i.e. I will leave the model configuration.

My full node version is 0.20 .0

```
chain=test

rpcauth=daniel:{YOUR-KEY-COOKIE}
rpcpassword:{YOUR-PASSWORD}

server=1
rest=1

[test]

deprecatedrpc=accounts
deprecatedrpc=addwitnessaddress
deprecatedrpc=signrawtransaction
deprecatedrpc=validateaddress

# daemon = 1
rpcbind = 0.0.0.0:18332
rpcallowip = 0.0.0.0/0

```
