### ISSUE TITLE
Never work properly.

### ISSUE THREAD

**Issue by block-hac** [ruimarinho/bitcoin-core#125]
I setup bitcoin-core on my server and it already synced mainnet.
```
Bitcoin-core version : 0.20.0
```
And then I made coding as follows:
```
const bitcoin_conf = {
    host: 'localhost',
    username: conf.rpc_user,
    password: conf.rpc_pwd,
    port: 8332,
    wallet: 'bitcoin-test',
    timeout: 30000
}

router.get('/blockchaininfo', async (req, res) => {
    var info = await client.getBlockchainInformation();
    console.log(info);
    res.json(info);
});
```
then it returns error like that : 
```
 UnhandledPromiseRejectionWarning: RpcError: Not Found
    at Parser.rest (/root/broker/bitcoin/node_modules/bitcoin-core/dist/src/parser.js:117:13)
    at Client.getBlockchainInformation (/root/broker/bitcoin/node_modules/bitcoin-core/dist/src/index.js:228:24)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /root/broker/bitcoin/src/methods.js:21:16
(Use `node --trace-warnings ...` to show where the warning was created)
(node:9536) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:9536) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by KayBeSee** [comment]
You're getting an error because `client.getBlockchainInformation` is not a valid function. It should be `client.getBlockchainInfo`

https://bitcoincore.org/en/doc/0.20.0/rpc/blockchain/getblockchaininfo/
