### ISSUE TITLE
RpcError: undefined Internal Server Error

### ISSUE THREAD

**Issue by SherlockStd** [ruimarinho/bitcoin-core#31]
Throwed exception from somewhere in my code ... can't even know where

```
RpcError: undefined Internal Server Error
    at Client.rpc (/home/ubuntu/project-back/node_modules/bitcoin-core/dist/src/parser.js:77:13)
    at Client.tryCatcher (/home/ubuntu/project-back/node_modules/bitcoin-core/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/ubuntu/project-back/node_modules/bitcoin-core/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/ubuntu/project-back/node_modules/bitcoin-core/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/ubuntu/project-back/node_modules/bitcoin-core/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/ubuntu/project-back/node_modules/bitcoin-core/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/home/ubuntu/project-back/node_modules/bitcoin-core/node_modules/bluebird/js/release/promise.js:638:18)
    at Request._callback (/home/ubuntu/project-back/node_modules/bitcoin-core/node_modules/bluebird/js/release/nodeback.js:45:21)
    at Request.self.callback (/home/ubuntu/project-back/node_modules/request/request.js:188:22)
    at emitTwo (events.js:130:20)
    at Request.emit (events.js:213:7)
    at Request. (/home/ubuntu/project-back/node_modules/request/request.js:1171:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage. (/home/ubuntu/project-back/node_modules/request/request.js:1091:12)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1059:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

**Comment by pedrobranco** [comment]
`RpcError: undefined Internal Server Error` is an error returned by the `bitcoind`, `bitcoin-core` client only parses it as an error and throws it.

You can add debug logs to check where is throwing. Care to see this [section](https://github.com/ruimarinho/bitcoin-core#logging).

**Comment by SherlockStd** [comment]
wow sorry too much time since I opened, didn't remember how I solved it.
Sorry again
