### ISSUE TITLE
Error: getaddrinfo ENOTFOUND

### ISSUE THREAD

**Issue by zss007** [ruimarinho/bitcoin-core#75]
Cannot connect to node, my config is like this:
```
{
    host: 'xx.com',
    ssl: true,
    port: 443,
    username: 'xx',
    password: 'xx',
}
```
And I get a error like this:
```
Unhandled rejection Error: getaddrinfo ENOTFOUND xx.com xx.com:443
    at errnoException (dns.js:50:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)
```

**Comment by uvios** [comment]
I am facing same issue @zss007 have you found a fix ?
