### ISSUE TITLE
Ctor is not a constructor

### ISSUE THREAD

**Issue by Dpk28** [ruimarinho/bitcoin-core#95]
When trying to use this function 

`const balance = await bitcoin.getBalance({
  account: 'miQqcznvHaS1dHvb38Nbhdp2i4FXhw5u9Y',
  minconf: 0
});`

It returns the following error: 

```
TypeError: Ctor is not a constructor
    at wrapper.<anonymous> (/Users/sc50119/Desktop/lcx/trading-engine/node_modules/lodash/lodash.js:4996:26)
    at apply (/Users/sc50119/Desktop/lcx/trading-engine/node_modules/lodash/lodash.js:474:27)
    at new wrapper (/Users/sc50119/Desktop/lcx/trading-engine/node_modules/lodash/lodash.js:5323:16)
    at /Users/sc50119/Desktop/lcx/trading-engine/server.js:65:25
    at Object.<anonymous> (/Users/sc50119/Desktop/lcx/trading-engine/server.js:70:3)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
```

**Comment by pedrobranco** [comment]
This issue seems unrelated with this module. You are still having issues?

**Comment by pedrobranco** [comment]
If you are still having this problem please reopen the issue.

**Comment by elmaedesistemas** [comment]
no news about this error?
